version: '3.8'
services:
  api:
    build: ./api # relative path to Dockerfile
    container_name: api_c # what to call our container
    ports:
      - '4000:4000' # port-mappings (there can be multiple)
    volumes:
      - ./api:/app # relative path of local machine to docker-compose-file
      - ./app/node_modules
  myblog:
    build: ./myblog
    container_name: myblog_c
    ports:
      - '3000:3000'
    stdin_open: true
